version: 0.2

# env:
#  parameter-store:
#    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
#    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
#    DOCKER_REGISTRY_URL: /myapp/docker-registry/url
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
      - echo "$username"
      - echo "$password"
      - echo "$password" | docker login -u "$username" --password-stdin "$url"
      - docker build -t "$url/$urername/python:latest" .
      - docker push  "$url/$urername/python:latest" 
  post_build:
    commands:
      - echo "Build completed successfully!"
