version: 0.2

env:
  parameter-store:
    username: /myapp/docker-credentials/username
    password: /myapp/docker-credentials/password
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
      - docker login -u "$username" -p "$password"
      - docker build -t "$username/python-app-awesome:latest" .
      - docker push  "$username/python-app-awesome:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"
